config/routes.rb
Rails.application.routes.draw do
  resources :registries
  resources :participants
  resources :coordinators
  root to:"registries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coordinator.rb
class Coordinator < ApplicationRecord
  has_many :registries
  has_many :participants, through: :registries
  validates :email , uniqueness:{ case_sensitive: false,message: "email already taken" }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :email, presence: true
  validates :phone_number, presence: true
  validates :name, presence: true
end

app/models/participant.rb
class Participant < ApplicationRecord
  has_many :registries
  has_many :coordinators, through: :registries

  validates :gender, presence: true
  validates :birthday, presence: true
end

app/models/registry.rb
class Registry < ApplicationRecord
  belongs_to :participant
  belongs_to :coordinator
  validates :name , uniqueness:{ case_sensitive: false,message: "name already taken" }
  validates :location , uniqueness:{ case_sensitive: false,message: "location already taken" }
  validates :name, presence: true
  validates :location, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coordinators_controller.rb
class CoordinatorsController < ApplicationController
  before_action :set_coordinator, only: %i[ show edit update destroy ]

  # GET /coordinators or /coordinators.json
  def index
    @coordinators = Coordinator.all
  end

  # GET /coordinators/1 or /coordinators/1.json
  def show
  end

  # GET /coordinators/new
  def new
    @coordinator = Coordinator.new
  end

  # GET /coordinators/1/edit
  def edit
  end

  # POST /coordinators or /coordinators.json
  def create
    @coordinator = Coordinator.new(coordinator_params)

    respond_to do |format|
      if @coordinator.save
        format.html { redirect_to coordinator_url(@coordinator), notice: "Coordinator was successfully created." }
        format.json { render :show, status: :created, location: @coordinator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coordinator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coordinators/1 or /coordinators/1.json
  def update
    respond_to do |format|
      if @coordinator.update(coordinator_params)
        format.html { redirect_to coordinator_url(@coordinator), notice: "Coordinator was successfully updated." }
        format.json { render :show, status: :ok, location: @coordinator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coordinator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coordinators/1 or /coordinators/1.json
  def destroy
    @coordinator.destroy

    respond_to do |format|
      format.html { redirect_to coordinators_url, notice: "Coordinator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coordinator
      @coordinator = Coordinator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coordinator_params
      params.require(:coordinator).permit(:name, :phone_number, :email)
    end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: %i[ show edit update destroy ]

  # GET /participants or /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1 or /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants or /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to participant_url(@participant), notice: "Participant was successfully created." }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1 or /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to participant_url(@participant), notice: "Participant was successfully updated." }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1 or /participants/1.json
  def destroy
    @participant.destroy

    respond_to do |format|
      format.html { redirect_to participants_url, notice: "Participant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def participant_params
      params.require(:participant).permit(:name, :gender, :birthday)
    end
end

app/controllers/registries_controller.rb
class RegistriesController < ApplicationController
  before_action :set_registry, only: %i[ show edit update destroy ]

  # GET /registries or /registries.json
  def index
    @registries = Registry.all
  end

  # GET /registries/1 or /registries/1.json
  def show
  end

  # GET /registries/new
  def new
    @registry = Registry.new
  end

  # GET /registries/1/edit
  def edit
  end

  # POST /registries or /registries.json
  def create
    @registry = Registry.new(registry_params)

    respond_to do |format|
      if @registry.save
        format.html { redirect_to registry_url(@registry), notice: "Registry was successfully created." }
        format.json { render :show, status: :created, location: @registry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @registry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registries/1 or /registries/1.json
  def update
    respond_to do |format|
      if @registry.update(registry_params)
        format.html { redirect_to registry_url(@registry), notice: "Registry was successfully updated." }
        format.json { render :show, status: :ok, location: @registry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @registry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registries/1 or /registries/1.json
  def destroy
    @registry.destroy

    respond_to do |format|
      format.html { redirect_to registries_url, notice: "Registry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registry
      @registry = Registry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def registry_params
      params.require(:registry).permit(:coordinator_id, :participant_id, :name, :location, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coordinators_helper.rb
module CoordinatorsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/registries_helper.rb
module RegistriesHelper
end

app/views/coordinators/_coordinator.html.erb
<div id="<%= dom_id coordinator %>">
  <p>
    <strong>Name:</strong>
    <%= coordinator.name %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= coordinator.phone_number %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= coordinator.email %>
  </p>

</div>

app/views/coordinators/_form.html.erb
<%= form_with(model: coordinator) do |form| %>
  <% if coordinator.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coordinator.errors.count, "error") %> prohibited this coordinator from being saved:</h2>

      <ul>
        <% coordinator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/coordinators/edit.html.erb
<h1>Editing coordinator</h1>

<%= render "form", coordinator: @coordinator %>

<br>

<div>
  <%= link_to "Show this coordinator", @coordinator %> |
  <%= link_to "Back to coordinators", coordinators_path %>
</div>

app/views/coordinators/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Coordinators</h1>

<div id="coordinators">
  <table class="table table-success table-hover">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">name</th>
      <th scope="col">email</th>
      <th scope="col">phone number</th>
      <th scope="col">Action</th>
    </tr>
    </thead>
    <tbody>
    <% @coordinators.each do |coordinator| %>
      <tr>
        <th scope="row"><%= coordinator.id%></th>
        <td><%= coordinator.name %></td>
        <td><%= coordinator.email%></td>
        <td><%= coordinator.phone_number%></td>
        <td><%= link_to 'info', coordinator_path(coordinator.id), class: "btn btn-outline-dark"%></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New coordinator", new_coordinator_path,class:"btn btn-outline-primary"  %>

app/views/coordinators/new.html.erb
<h1>New coordinator</h1>

<%= render "form", coordinator: @coordinator %>

<br>

<div>
  <%= link_to "Back to coordinators", coordinators_path %>
</div>

app/views/coordinators/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @coordinator %>

<div>
  <%= link_to "Edit this coordinator", edit_coordinator_path(@coordinator) %> |
  <%= link_to "Back to coordinators", coordinators_path %>

  <%= button_to "Destroy this coordinator", @coordinator, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Task10</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <div class="container-fluid ">
    <a class="navbar-brand" href="#">ruby on rails</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="/registries">Registries</a>
        <a class="nav-link active" href="/coordinators">Coordinators</a>
        <a class="nav-link active" href="/participants">Participants</a>

      </div>
    </div>
  </div>
</nav>
<body>
<%= yield %>
</body>
</html>

app/views/participants/_form.html.erb
<%= form_with(model: participant) do |form| %>
  <% if participant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
        <% participant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.select :gender, ['Male', 'Female']%>
  </div>

  <div>
    <%= form.label :birthday, style: "display: block" %>
    <%= form.date_field :birthday %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/participants/_participant.html.erb
<div id="<%= dom_id participant %>">
  <p>
    <strong>Name:</strong>
    <%= participant.name %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= participant.gender %>
  </p>

  <p>
    <strong>Birthday:</strong>
    <%= participant.birthday %>
  </p>

</div>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render "form", participant: @participant %>

<br>

<div>
  <%= link_to "Show this participant", @participant %> |
  <%= link_to "Back to participants", participants_path %>
</div>

app/views/participants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Participants</h1>

<table class="table table-success table-hover">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Birthday</th>
    <th scope="col">Gender</th>
    <th scope="col">Action</th>
  </tr>
  </thead>
  <tbody>
  <% @participants.each do |participant| %>
    <tr>
      <th scope="row"><%= participant.id %></th>
      <td><%= participant.name %></td>
      <td><%= participant.birthday %></td>
      <td><%= participant.gender%></td>
      <td><%= link_to 'info', participant_path(participant.id), class: "btn btn-outline-dark"%></td>
    </tr>
    <tr>
  <%end%>
  </tbody>
</table>

<%= link_to "New participant", new_participant_path,class:"btn btn-outline-primary" %>

app/views/participants/new.html.erb
<h1>New participant</h1>

<%= render "form", participant: @participant %>

<br>

<div>
  <%= link_to "Back to participants", participants_path %>
</div>

app/views/participants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @participant %>

<div>
  <%= link_to "Edit this participant", edit_participant_path(@participant) %> |
  <%= link_to "Back to participants", participants_path %>

  <%= button_to "Destroy this participant", @participant, method: :delete %>
</div>

app/views/registries/_form.html.erb
<%= form_with(model: registry) do |form| %>
  <% if registry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(registry.errors.count, "error") %> prohibited this registry from being saved:</h2>

      <ul>
        <% registry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :coordinator_id, style: "display: block" %>
    <%= form.select :coordinator_id, Coordinator.all.pluck(:name, :id)%>
  </div>

  <div>
    <%= form.label :participant_id, style: "display: block" %>
    <%= form.select :participant_id, Participant.all.pluck(:name, :id)%>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.check_box :state %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/registries/_registry.html.erb
<div id="<%= dom_id registry %>">
  <p>
    <strong>Coordinator:</strong>
    <%= registry.coordinator_id %>
  </p>

  <p>
    <strong>Participant:</strong>
    <%= registry.participant_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= registry.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= registry.location %>
  </p>

  <p>
    <strong>State:</strong>
    <%= registry.state %>
  </p>

</div>

app/views/registries/edit.html.erb
<h1>Editing registry</h1>

<%= render "form", registry: @registry %>

<br>

<div>
  <%= link_to "Show this registry", @registry %> |
  <%= link_to "Back to registries", registries_path %>
</div>

app/views/registries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Registries</h1>

<table class="table table-success table-hover">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Coordinator</th>
    <th scope="col">Participant</th>
    <th scope="col">Name</th>
    <th scope="col">Location</th>
    <th scope="col">State</th>
    <th scope="col">Action</th>
  </tr>
  </thead>
  <tbody>
  <% @registries.each do |registry| %>
    <tr>
      <th scope="row"><%= registry.id %></th>
      <td><%= registry.coordinator_id %></td>
      <td><%= registry.participant_id %></td>
      <td><%= registry.name %></td>
      <td><%= registry.location %></td>
      <td><%= registry.state %></td>

      <td><%= link_to 'info', registry_path(registry.id), class: "btn btn-outline-dark"%></td>
    </tr>
    <tr>
  <%end%>
  </tbody>
</table>

<%= link_to "New registry", new_registry_path,class:"btn btn-outline-primary"  %>

app/views/registries/new.html.erb
<h1>New registry</h1>

<%= render "form", registry: @registry %>

<br>

<div>
  <%= link_to "Back to registries", registries_path %>
</div>

app/views/registries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @registry %>

<div>
  <%= link_to "Edit this registry", edit_registry_path(@registry) %> |
  <%= link_to "Back to registries", registries_path %>

  <%= button_to "Destroy this registry", @registry, method: :delete %>
</div>